name: unsplash
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  flutter_staggered_grid_view: ^0.7.0
  dio: ^5.3.3
  json_annotation: ^4.8.1
  provider: ^6.1.0
  webview_flutter: ^4.4.2
  webview_flutter_android: ^3.12.1
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.9


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.6

flutter:
  assets:
    - assets/
  uses-material-design: true